### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Viniccius157** [ArachisH/Geode#1]
I'm trying to use Geode to make my extensions compatible to G-Earth, but I keep getting the error 'System.ArgumentOutOfRangeException' in mscorlib.dll.

Messing around with the source of Geode, I found out the error is in the ReadUInt16 method:
![image](https://user-images.githubusercontent.com/34200697/51489714-431d4a80-1d90-11e9-993a-29931b356859.png)

But only happens when it tries to read the ID of a EvaWire packet:
![image](https://user-images.githubusercontent.com/34200697/51489763-66e09080-1d90-11e9-9419-0d22739621d0.png)

![image](https://user-images.githubusercontent.com/34200697/51489737-50d2d000-1d90-11e9-9b88-ba0292592b08.png)

**Comment by ArachisH** [comment]
This is most likely due to the current incompatibility between the two, but it should work after the next G-Earth update.
